version: 0.2

phases:
  install:
      commands:
         - echo comando de instalacion ...
  build:
       commands:
         - echo Build started on `date`
         - echo Compiling some code...
         
  post_build:
       commands:
         - echo Build completed on `date`