version: 0.2

phases:
  install:
      commands:
         - echo comando de instalacion ...
  build:
       commands:
         - echo Build arrancando `date`
         - echo Compilando un codigo...
         
  post_build:
       commands:
         - echo Build completed on `date`